### ISSUE TITLE
[Homolog] Testar Multi Diligência

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#112]
## **Contexto**

- Ultima release foi atualizada e devemos realizar os testes da versão.

## **Objetivo**

**Como** uma pessoa testadora do mapa cultural
**Quero** realizar os testes da última release da Multi diligência
**Para** ter a certeza que não tem bug críticos ou se terá algo para melhorar

## **Escopo**

- [x] escopo1

## **Fora de Escopo**

- fora_de_escopo

## Para testar

- [x] Fluxo da Multi diligência com envio de arquivos
- [x] Aba Em Diligência mostrando o status da diligência #22 
- [x] Opções de configuração da diligência #78 
- [x] Valida se o usuário é um admin da oportunidade #41 
- [x] Multi diligência apenas para oportunidade documental #59 
- [x] Remoção da edição do período de diligência após o envio da mesma #66 
- [x] Adicionado campo com valor do projeto a planilha de avaliações #80 

# Observações
E-mails: http://172.21.4.11:8026/

**Comment by Yasminemaciel02** [comment]
![image](https://github.com/secultce/mapasculturais-v5/assets/167997705/0c94cc40-7f64-4f80-be48-81bd46e9c311)
Multi diligência não aparece na configuração da avaliação documental, conforme issue #59

**Comment by Yasminemaciel02** [comment]
![image](https://github.com/secultce/mapasculturais-v5/assets/167997705/7926f7f2-2d64-45f4-8e41-9f72529bab6d)

**Comment by Yasminemaciel02** [comment]
![image](https://github.com/secultce/mapasculturais-v5/assets/167997705/31609565-5080-4bd2-ba86-cac3d03d5208)
Após interação de diligência não é possível realizar edição, conforme #66

**Comment by Yasminemaciel02** [comment]
Fluxo inteiro funcionando conforme os requisitos.
